# Etapa de construcción: Instalación de dependencias y creación del paquete de producción
FROM node:22 as build

WORKDIR /app

# Copia los archivos package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos de la aplicación
COPY . .

# Construye la aplicación
RUN npm run build

# Etapa de producción: Servidor Nginx con la aplicación compilada
FROM nginx:stable-alpine

# Copia los archivos compilados de la aplicación
COPY --from=build /app/dist /usr/share/nginx/html

# Configuración personalizada de Nginx directamente en el Dockerfile
COPY ./deploy/nginx/nginx.config /etc/nginx/conf.d/default.conf