// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PermissionManager.Core.Models;

public partial class Permission
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int PermissionTypeId { get; set; }

    public DateOnly PermissionDate { get; set; }

    public virtual PermissionType PermissionType { get; set; }
}