// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PermissionManager.Core.Models;

public partial class PermissionType
{
    public int Id { get; set; }

    public string Description { get; set; }
    public string Name { get; set; }

    public virtual ICollection<Permission> Permissions { get; set; } = new List<Permission>();
  
}