version: '3'
services:
  frontend-permission-manager:
    build:
      context: .
      dockerfile: ./projects/AccesManager/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run preview
    environment:
      - REACT_APP_API_URL=http://permission-manager-api:7130

networks:
  distrib-api-net:
     external: true