version: '3.8'

services:
  elasticsearch:
    extends:
      file: ./elasticSearch/docker-compose.yml
      service: setup

  kafka:
    extends:
      file: ./Kafka/docker-compose.yml
      service: zookeeper

  Backend:
    extends:
      file: ./Backend/docker-compose.yml
      service: permission-manager-api