version: '3.8'

services:
  permission-manager-api:
    build:
      context: .
      dockerfile: ./PermissionManager/PermissionManager.API/Dockerfile
    ports:
      - "7130:7130"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Data Source=sqlserver;Initial Catalog=ChallengeN5;User ID=sa;Password=Kawasaki2512;MultipleActiveResultSets=True;Connect Timeout=100;Encrypt=False;Current Language=spanish
      - ElasticSearchAuthConfig__Url=https://es01:9200
      - ElasticSearchAuthConfig__username=elastic
      - ElasticSearchAuthConfig__password=changeme
      - Kafka__BootstrapServers=kafka:9092
      - Kafka__GroupId=permission-group
    depends_on:
      - sqlserver
    networks:
      - kafka-network
      - elastic
      - distrib-api-net

  permission-manager-consumer:
    build:
      context: .
      dockerfile: ./PermissionManager/PermissionManager.Consumers/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Data Source=sqlserver;Initial Catalog=ChallengeN5;User ID=sa;Password=Kawasaki2512;MultipleActiveResultSets=True;Connect Timeout=100;Encrypt=False;Current Language=spanish
      - ElasticSearchAuthConfig__Url=https://es01:9200
      - ElasticSearchAuthConfig__username=elastic
      - ElasticSearchAuthConfig__password=changeme
      - Kafka__BootstrapServers=kafka:9092
      - Kafka__GroupId=permission-group
    depends_on:
      - sqlserver
      
    networks:
      - kafka-network
      - elastic
      - distrib-api-net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Kawasaki2512"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - kafka-network
      - elastic
      - distrib-api-net
networks:
  kafka-network:
    external: true
  elastic:
    external: true
  distrib-api-net:
    driver: bridge
